### PR TITLE
Added Persian (fa) Locale

### PR DESCRIPTION
**Pull request by ehsanr-r**
I added a new strings.xml file to support the Persian language.

### CODE REVIEW

**Comment by Arrowsome** [comment]
There are multiple other pull request like this, you could've checked theme before making a pull request. #739 #642.

**Comment by arriolac** [comment]
Thanks for the contribution! There are a couple more strings missing:
* `a11y_plant_item_image`
* `a11y_back`

**Review by arriolac — APPROVED** [review]
LGTM. Please sign CLA and will merge in. Thanks!

**Comment by arriolac** [comment]
CLA still failing (see https://github.com/android/sunflower/pull/751/checks?check_run_id=19988830749). Alternatively, you can open a new PR with a commit signed by an email address you used to sign the CLA.

**Comment by riggaroo** [comment]
Hi, 
Thanks for your contribution, however Sunflower is going to be archived in favour of maintaining a smaller set of up-to-date set of compose-samples, that can be found here: https://github.com/android/compose-samples, as well as snippets that can be found here: https://github.com/android/snippets.

Please feel free to keep your fork up-to-date for your learning, but this repository will be archived shortly.

**Pull request closed without merging**
