### PR TITLE
Fix #96: A potential mem-leak when call providePlantDetailViewModelFactory

### LINKED ISSUE #96: Will passing context to InjectorUtils singleton object cause memory leaks
If we send activity/fragment context to InjectorUtils singleton object, will they hold a reference to it even after they've been destroyed and lead to memory leaks?

Please clarify

### PR DESCRIPTION
**Pull request by XinyueZ**
See #96

### CODE REVIEW

**Comment by andhie** [comment]
wouldnt it be better to enforce passing in `Application`? by changing all the InjectorUtils params to accept `Application` instead of just `Context`
we can see this style in `AndroidViewModel` that enforces to pass `Application`
https://developer.android.com/reference/androidx/lifecycle/AndroidViewModel#androidviewmodel

**Comment by yshrsmz** [comment]
why not just call `context.applicationContext` inside `InjectorUtils`?

**Comment by XinyueZ** [comment]
@andhie I want to here code against the interface(Context) instead of a concrete class. thank u for the tip @yshrsmz

**Comment by XinyueZ** [comment]
I have resolved conflicts .

**Comment by nic0lette** [comment]
Thanks again for the contribution. :)

**Pull request merged**
