### PR TITLE
Converted the findviewbyid to databinding to match the mvvm architecture

### PR DESCRIPTION
**Pull request by bhaarn**
Converted the findviewbyid to databinding to match the mvvm architecture

### CODE REVIEW

**Comment by tiembo** [comment]
Thanks for your PR.  Can you work with @XinyueZ as he has some databinding PRs open as well?

**Comment by bhaarn** [comment]
@tiembo Thanks for you comments.  Will connect with @XinyueZ

**Comment by bhaarn** [comment]
@XinyueZ I had fixed some of the findviewbyid logic to databinding.  Can you please review this.  Also I am getting some formatting issue in CI for the code I had comitted.  Should I use any plugin to fix the styling ?

**Comment by XinyueZ** [comment]
@bhaarn There's some ktlint blocks please check with running `gradlew spotlessApply` .

**Comment by XinyueZ** [comment]
@bhaarn The branches  https://github.com/googlesamples/android-sunflower/pull/25 https://github.com/googlesamples/android-sunflower/pull/14 are including optimized data-binding & MVVM solution.

When you want you can pull these codes into your branch and we do these together!

**Comment by bhaarn** [comment]
@XinyueZ I saw your branches #25  #14  and all the fix done by me are already in place.  So I am not merging the code.  You please go forward and commit the changes in #25  #14 .  Once you are Ok, You can close the ticket #144 .

**Comment by tiembo** [comment]
Hi @bhaarn - PRs #14 and #25 have been closed as some data binding changes have been implemented.  Do you want to continue with this branch or close it? cc @XinyueZ

**Comment by XinyueZ** [comment]
I'm OK! 👍

**Comment by tiembo** [comment]
Closing PR - please comment if this should be readdressed.  Thanks!

**Pull request closed without merging**
