### PR TITLE
[UPDATE] Work 2.1.0

### PR DESCRIPTION
**Pull request by XinyueZ**

### CODE REVIEW

**Comment by XinyueZ** [comment]
@tiembo I think this failed can bring a topic as bug-report for Google, right?

**Comment by tiembo** [comment]
@XinyueZ per the [release notes](https://developer.android.com/jetpack/androidx/releases/work#2.1.0) work-runtime-ktx now requires Java 8.  Can you add the following lines to line 47 in `app/build.gradle`?

```
    // work-runtime-ktx 2.1.0 and above now requires Java 8
    kotlinOptions { 
        jvmTarget = "1.8"
    }
```

**Comment by XinyueZ** [comment]
> @XinyueZ per the [release notes](https://developer.android.com/jetpack/androidx/releases/work#2.1.0) work-runtime-ktx now requires Java 8. Can you add the following lines to line 47 in `app/build.gradle`?
> 
> ```
>     // work-runtime-ktx 2.1.0 and above now requires Java 8
>     kotlinOptions { 
>         jvmTarget = "1.8"
>     }
> ```

got it

**Comment by tiembo** [comment]
Thanks!

**Pull request merged**
