### PR TITLE
Support display with Cutout-Mod(fullscreen app)

### PR DESCRIPTION
**Pull request by XinyueZ**

### CODE REVIEW

**Comment by tiembo** [comment]
The title is overlapped on an emulated Pixel 2
screenshot_1537077522

**Comment by XinyueZ** [comment]
I have done some changes addressed by https://github.com/googlesamples/android-sunflower/issues/163#issuecomment-421829653

**Comment by XinyueZ** [comment]
solved conflicts

**Comment by tiembo** [comment]
Closing due to closing of issue #163

**Pull request closed without merging**
