### PR TITLE
Fix Room FK warnings

### PR DESCRIPTION
**Pull request by andhie**
> w:app/build/tmp/kapt3/stubs/debug/com/google/samples/apps/sunflower/data/GardenPlanting.java:15: warning: plant_id column references a foreign key but it is not part of an index. This may trigger full table scans whenever parent table is modified so you are highly advised to create an index that covers this column.

### CODE REVIEW

**Comment by tiembo** [comment]
Thanks for the PR!  Since Sunflower is currently in alpha let's omit the migration and keep just the FK. 
 The DB and schema will likely change often so migrations should only be used once the project is stable.

I'll update the README to explicitly point out non-backwards compatible changes while the project is in alpha.

**Comment by andhie** [comment]
would you prefer to use `fallbackToDestructiveMigration` instead?

**Comment by tiembo** [comment]
While adding `fallbackToDestructiveMigration` would work and prevent the app from crashing, I'm concerned that it'll be forgotten and overlooked, causing some odd behavior in the future.

I added the warning about not maintaining backwards compatibility in #118.  If it's OK with you let's merge this PR with just the FK fix.

**Comment by andhie** [comment]
no problem for me. do merge

**Comment by tiembo** [comment]
Thanks!

**Pull request merged**
