### PR TITLE
Fix #132: the PlantAndGardenPlantingsViewModel decoupled from context and string-resource

### LINKED ISSUE #132: Fix resolving strings in ViewModel
ViewModel should not be resolving strings from resources as shown in 
https://github.com/googlesamples/android-sunflower/blob/4c8d9045d9662e5c659c9ee3dafc66d993e28968/app/src/main/java/com/google/samples/apps/sunflower/viewmodels/PlantAndGardenPlantingsViewModel.kt

If user changes locale on device, activity/fragment will be recreated but ViewModel will be retained with data, that might be invalid for new configuration/locale. Because this is sample referenced by official google documentation, it should not be showcasing invalid ViewModel usage. 

> The Sunflower demo app demonstrates best practices with architecture components.
https://developer.android.com/topic/libraries/architecture/

ref. https://issuetracker.google.com/u/1/issues/111961971

### PR DESCRIPTION
**Pull request by XinyueZ**
This bug is critical and obscure, there's already issue on Google, see also:
- https://github.com/googlesamples/android-sunflower/issues/132
- https://issuetracker.google.com/u/2/issues/111961971

@tiembo I think this fix is important for this project which is the official demo to declare how people use the [Jetpack](https://developer.android.google.cn/jetpack/), so please check out.

### CODE REVIEW

**Comment by tiembo** [comment]
There are some lint issues.

**Comment by XinyueZ** [comment]
@tiembo problem and conflicts solved.

**Comment by tapanrgohil** [comment]
PlantAndGardenPlantingsViewModel is still not fixed.
it's still using Context inside view model either it't not using Android view model according android docs.
https://developer.android.com/topic/libraries/architecture/viewmodel

**Comment by XinyueZ** [comment]
@tapanrgohil this PR should have fixed.

**Comment by XinyueZ** [comment]
@nic0lette @tiembo can take a look at this fix?

**Comment by JoseAlcerreca** [comment]
Removing context from the VM parameters is a good thing!

Have you considered a Binding Adapter to avoid that huge layout expression?

`android:text="@{@string/water_date(@string/watering_next_prefix(viewModel.waterDateString), @plurals/watering_next_suffix(viewModel.wateringInterval, viewModel.wateringInterval))}"`

**Comment by dazza5000** [comment]
Is there an example on unit testing binding adapters?

**Comment by XinyueZ** [comment]
> Removing context from the VM parameters is a good thing!
> 
> Have you considered a Binding Adapter to avoid that huge layout expression?
> 
> `android:text="@{@string/water_date(@string/watering_next_prefix(viewModel.waterDateString), @plurals/watering_next_suffix(viewModel.wateringInterval, viewModel.wateringInterval))}"`

Would you mind that I can do this in a separated PR to optimize Binding Adapter?

**Comment by nic0lette** [comment]
Thanks :)

**Comment by JoseAlcerreca** [comment]
@dazza5000 they're static methods so if you mock the View they should be easy to test. Have you found a specific problem?

**Comment by XinyueZ** [comment]
I prefer `BindingAdapter` in extension way instead `static`. 


```kotlin
hello(view: View, s: String) {
}
---->
View.hello(s: String) {
}
```

**Comment by JoseAlcerreca** [comment]
So? You can still call them from tests.

fun test1() {
    val view = Mock...
    view.someAdapter(4)
    verify(...)
}

fun View.someAdapter(g: Int) {

}

**Comment by XinyueZ** [comment]
Actually, basically, if I use extension style I can mochito them

> So? You can still call them from tests.
> 
> fun test1() {
> val view = Mock...
> view.someAdapter(4)
> verify(...)
> }
> 
> fun View.someAdapter(g: Int) {
> 
> }

**Pull request merged**
