### PR TITLE
Update `SeedDatabaseWorker.kt`

### PR DESCRIPTION
**Pull request by ibrahimAlii**
Update navigationVersion to '1.0.0-alpha09' & constraintLayoutVersio to '2.0.0-alpha3'

### CODE REVIEW

**Comment by tiembo** [comment]
Hi @ibrahimAlii , thanks for your contribution!  In order to keep PRs small and focused, can you move the non-navigation and constraint layout changes to another PR?

**Comment by ibrahimAlii** [comment]
@tiembo  OK, I will.

**Comment by tiembo** [comment]
Hi @ibrahimAlii - I opened a PR with just the Navigation and the Constraint Layout updates in #297.  Feel free to re-use this PR for your `SeedDatabaseWorker.kt` changes.

**Comment by XinyueZ** [comment]
@ibrahimAlii  I had already some updates in worker #201, take a look to find difference which might help you more.

**Comment by tiembo** [comment]
Hi @ibrahimAlii , thanks again for this PR.  #201 already implements these changes.

**Pull request closed without merging**
