### PR TITLE
Refactor some build logic to the buildSrc & gradle kotlin-dsl

### PR DESCRIPTION
**Pull request by jmfayard**
Refactor some build logic to the buildSrc & gradle kotlin-dsl

Files buildSrc/src/main/java/{Versions.kt,Libs.kt} generated by kotlinpoet and the task
   $ `./gradlew syncLibs`

See https://blog.kotlin-academy.com/gradle-kotlin-the-missing-piece-of-the-puzzle-7528a85f0d2c

### CODE REVIEW

**Comment by jmfayard** [comment]
Mmh, test `PlantTest#test_shouldBeWatered` is working on my computer but is failing on CircleCI. 
I don't find the artifacts on CircleCi to find out why. 
Any help?

**Comment by jmfayard** [comment]
@tiembo anyway I have a good grasp now on Gradle's Kotlin DSL. 
If that's a topic you are interested in, I can update and improve this pull request. 

If not, that's also fine. I used a few projects like yours to make sure that my plugin  https://github.com/jmfayard/gradle-kotlin-dsl-libs works correctly, which seems to be the case :)

**Comment by XinyueZ** [comment]
@jmfayard could you please resolve conflicts, I am personally as one of fans of dsl.

**Comment by jmfayard** [comment]
@XineyueZ done

**Comment by XinyueZ** [comment]
@jmfayard I think you need format code 🌦

**Comment by jmfayard** [comment]
@XinyueZ done. 
Nice thing, I will use it to my projects too

**Comment by tiembo** [comment]
Hi @jmfayard , apologies for the delay in replying.

I like the Kotlin DSL but feel that it's beyond the scope of this Jetpack-focused sample.  Happy to note this PR in the README or Wiki as an sample of implementing gradle-kotlin-dsl-libs.  Would that work?

**Comment by jmfayard** [comment]
@tiembo no big problem for me, I needed repositories to test my plugin with anyway, so that part is mission accomplished. 

Just for completion, I realize that putting `kotlin dsl` in the name of my plugin a bit of a misnommer. 

I think that writing Gradle builds in Kotlin instead of Groovy is the future, but writing them in Groovy is the present, and I wouldn't actually recommend rewriting any existing build just for the sake of the rewrite. In the end, it's just the same Gradle build. 

What I'm instead doing for my own projects (and it's a Gradle best practice by the way)
- Keep the existing build.gradle files, especially the parts in it that are nice and declarative.
- Find the parts from the build files that look like Groovy code, and extract that build logic to that special `buildSrc` Gradle module. And *there* I use Kotlin.

**Comment by tiembo** [comment]
Referenced this PR in the [wiki](https://github.com/googlesamples/android-sunflower/wiki/Sunflower-additional-resources#community-contributions).

**Pull request closed without merging**
