### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by sagar-viradiya**
GardenActivity and README cleanup

### CODE REVIEW

**Comment by tiembo** [comment]
The README license should stay unchanged as to match the licenses from other samples.

**Comment by sagar-viradiya** [comment]
Cool, reverting it

**Comment by tiembo** [comment]
The revert also removed files from the `.idea` directory - we only want the changes for `GardenActivity` in this PR.

**Comment by sagar-viradiya** [comment]
Yeah sorry, may bad. Fixing...

**Comment by sagar-viradiya** [comment]
Done

**Comment by tiembo** [comment]
Thanks!

**Pull request merged**
